name: rwg-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - streamlit>=1.26
      - pydantic>=2.0
      - numpy
      - spacy
      - sentence-transformers
      - google-generativeai
      - biopython
      - bitstring
      - python-dotenv
      - tqdm
      - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz