name: rwg-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11        # 3.11 is supported by spaCy
  - pip
  - pip:
      - numpy<2
      - spacy==3.7.4
      - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
      - sentence-transformers
      - streamlit>=1.26
      - google-generativeai
      - biopython
      - bitstring
      - python-dotenv
      - tqdm
      - pydantic>=2.0
